FROM node:18
WORKDIR /app

# Copy and install dependencies
COPY ../package*.json ./
RUN npm install

# Copy server files
COPY . ./

# Expose port the server listens on
EXPOSE 5000

# Start the backend server
CMD ["npm", "run", "dev"]
