version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:q7GnG556aZHYa@db.aerjravmccadudskvhel.supabase.net:5432/postgres
    restart: unless-stopped
