services:
  frontend:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "4000:4000"
    restart: unless-stopped
